### PR TITLE
[feature] key management (import / export)

### PR DESCRIPTION
**Pull request by ereio**
### Types
- [ ] Fix (non-breaking change which fixes an issue)
- [x] Feature (non-breaking change which adds functionality)
- [x] Refactor (non-breaking change which improves code quality - QA thoroughly )
- [ ] Breaking Change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Chore (updates that would not affect or change the code involving the app itself)

### TODO
- Add sessions to existing ones, don't overwrite
- Migrate existing sessions in old crypto state to new state

#### 🔮 Features
- Import Session Keys
- Export Session Keys

### QA

- [x] Signup
- [x] Login
- [x] Logout
- [ ] Unencrypted Chat 
- [x] Encrypted Chat 
- [ ] Group Chats
- [ ] Profile Changes
- [ ] Theming Changes
- [ ] Force Kill and Restart

### Final Checklist
 
- [ ] All associated issues have been linked to PR
- [ ] All necessary changes made to the documentation
- [ ] Parties interested in these changes have been notified

### CODE REVIEW

**Comment by ereio** [comment]
@EdGeraghty @0x1a8510f2 if you both could find time soon, would love for a few more people to help test both import and export now. I've only run tests on test accounts specifically, but I'll be testing with my mains after tonight. Hope to get any other issues worked out before next weekend! :)

Couple thoughts

- this implementation currently allows imports after you've already started a new session, and potentially established a new set of megolm keys for a chat. There may be conflicts with deciding which keys to send messages with, though at a glance, it should prioritize the newer ones correctly.

- if prioritization fails, what are both of your thoughts on having a "Would you like to import a backup?" dialog upon login before heading to the `home` screen? I'm pretty divided on it personally, but I think it would ultimately be a better user experience (would honestly operate a lot like Signal does). Let me know your thoughts!

**Comment by 0x1a8510f2** [comment]
Happy to test soon but it seems https://git.syphon.org/syphon-org/syphon/releases doesn't have an Android build for commit 13536518fade92e9b7a400f7bb41d11999c6eca8 and I currently don't have time to build from source ( my flutter VM broke and I need to rebuild :/ ).

>what are both of your thoughts on having a "Would you like to import a backup?" dialog upon login before heading to the `home` screen? I'm pretty divided on it personally, but I think it would ultimately be a better user experience (would honestly operate a lot like Signal does). Let me know your thoughts!

A dedicated key import screen/dialog feels a little overkill but maybe a quickstart suggestion screen could be good? For instance, if the user logged in, suggest:
- Importing keys
- Customising the theme
- Adding another account
- Checking active sessions for security purposes

If they registered suggest:
- Changing username/profile pic
- Adding users
- Creating rooms
- Customising theme
- Adding email/phone number

With each option linked to the relevant setting. I'm somewhat basing the idea on Android's setup where the last page gives you some settings you may want to play around with.

**Comment by ereio** [comment]
Thanks for all the thoughts above, I largely agree.

> the initial sync is hidden behind this screen so if the user chooses to play around with some settings, they won't even notice the sync.

This is a great idea. I had intended for onboarding to work pretty similar, though you'd be able to see your chat list syncing beneath the backdrop of the highlights / dialogs. 

Might be time to being implementing onboarding then.

Below is a successful build, for android, for the latest commit. Let me know if you get around to trying it out

https://git.syphon.org/syphon-org/syphon/releases/tag/feature/key-management-1353651-android

**Comment by 0x1a8510f2** [comment]
>Might be time to being implementing onboarding then.

That sounds like a good idea IMO :D

>Let me know if you get around to trying it out

Fortunately, I have a minute right now! :D

Testing done on:
- Android 11 (OxygenOS)
- OnePlus Nord CE 5G
- matrix.0x1a8510f2.space homeserver (Dendrite)
- Linked build

My findings (mostly just a brain dump of everything that seemed off - I have to be leaving the house soon so no time to clean it up :P):
- Almost certainly unrelated but the app freezes briefly after entering the full username. I assume this is because it's running the ".well-known" check as a notification about that shows up soon after. Mentioning just in case cause I'll probably forget to open a dedicated issue.
- Minor detail, but it may be worth renaming "Privacy" settings to "Privacy & Security" given that encryption stuff is in there now.
- The app freezes when backing up keys (and importing too) for a while and then shows a green success banner, but I haven't yet been able to figure out where the keys are backed up to 😅. It only requests file permissions when trying to import keys.
- The backup/import password prompt is plaintext. This is probably fine, but it may still be worth adding a "mask" button like most password prompts.
- When the import password is wrong, the error is much less readable/user-friendly than the success message.
- Weirdly, in a DM between my main and testing accounts, when I logged out from Syphon on my testing account and logged back in, then imported the keys I exported from Element logged into the same account, only the testing account's messages seemed to get decrypted. Repeating this decrypted the previous messages from my main but not the latest. Not sure if this is Syphon's fault or Element's for not including the latest keys, but I attach a screenshot to show what I mean:
Screenshot
(The topmost incoming message is not included in the backup, the next is the one which didn't decrypt initially but did after another cycle, and the following are those which were sent during the second cycle and then weren't decrypted).

On the plus side:
- The file picker dialogue, when importing keys, greys out all incompatible files, which is great.
- Parsing of Element's exports works flawlessly

**Comment by ereio** [comment]
thanks a ton for this, should be able to tidy this branch up on Sunday. Would guess it's a bug on my end!

**Comment by ereio** [comment]
> - Minor detail, but it may be worth renaming "Privacy" settings to "Privacy & Security" given that encryption stuff is in there now.
> - The app freezes when backing up keys (and importing too) for a while and then shows a green success banner, but I haven't yet been able to figure out where the keys are backed up to 😅. It only requests file permissions when trying to import keys.
> - The backup/import password prompt is plaintext. This is probably fine, but it may still be worth adding a "mask" button like most password prompts.
> - When the import password is wrong, the error is much less readable/user-friendly than the success message.

Completed these, but the following

> Weirdly, in a DM between my main and testing accounts, when I logged out from Syphon on my testing account and logged back in, then imported the keys I exported from Element logged into the same account, only the testing account's messages seemed to get decrypted. Repeating this decrypted the previous messages from my main but not the latest. Not sure if this is Syphon's fault or Element's for not including the latest keys, but I attach a screenshot to show what I mean

Is the result of not supporting multiple active sessions _per device_. Will require a decent sized change, going to try to finish up today but this may kick the release :/

**Comment by ereio** [comment]
Note regression changes made under

https://github.com/syphon-org/syphon/pull/509/commits/1428ef9a12e183a3803f1d3156cfaef2e28662af

Will need to figure out why certain config affects `ninja` builds on macos

**Comment by ereio** [comment]
I felt confident merging, but if you both could check it out I'd appreciate it! :)

**Pull request merged**
