### PR TITLE
[chore] flutter 3.7.10 build

### LINKED ISSUE #744: Adjust the dependency of vector_math
Currently syphon has these two dependencies in pubspec.yaml:
```
dependencies:
  ...
  flutter_localizations:
    sdk: flutter
  ...
  vector_math: 2.1.2
  ...
```
While `flutter_localizations` itself depends on another version of `vector_math`, namely 2.1.4:
```
dependencies:
  ...
  vector_math: 2.1.4
  ...

(Find more in https://github.com/flutter/flutter/blob/master/packages/flutter_localizations/pubspec.yaml)
```
As a result, executing `flutter pub get` or `flutter pub upgrade` alike ends up in:
```
flutter pub upgrade
Resolving dependencies...
Because syphon depends on flutter_localizations from sdk which depends on vector_math 2.1.4, vector_math 2.1.4 is required.
So, because syphon depends on vector_math 2.1.2, version solving failed.
pub finished with exit code 1
```
Is it appropriate to update the dependency of `vector_math` now?

### PR DESCRIPTION
**Pull request by EdGeraghty**
### Types
- [x] Fix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [x] Refactor (non-breaking change which improves code quality - QA thoroughly )
- [ ] Breaking Change (fix or feature that would cause existing functionality to not work as expected)
- [x] Chore (updates that would not affect or change the code involving the app itself)

### Changes
Massive plugin version rollup, and fixes to get it building.

### QA

- [ ] Signup
- [ ] Login
- [ ] Logout
- [ ] Unencrypted Chat 
- [ ] Encrypted Chat 
- [ ] Group Chats
- [ ] Profile Changes
- [ ] Theming Changes
- [ ] Force Kill and Restart

### Final Checklist
 
- [ ] All associated issues have been linked to PR
- [ ] All necessary changes made to the documentation
- [ ] Parties interested in these changes have been notified
- [x] Linter has been run on all code in the PR

### CODE REVIEW

**Review by ereio — APPROVED** [review]
Awesome job! @EdGeraghty!

Want to confirm, is this Windows only or did you get a successful build on a linux distro too?

**Comment by EdGeraghty** [comment]
I have tested on Win10 only. I will confirm it builds on Debian shortly.

**Comment by EdGeraghty** [comment]
Screenshot_2023-04-13_12-10-14

**Comment by EdGeraghty** [comment]
🎉

**Pull request merged**
