### PR TITLE
Android system UI tweaks

### PR DESCRIPTION
**Pull request by TR-SLimey**
The Android system UI (navbar and notification bar) seems to stick out a bit in-app, so I made it same colour as the splash background on the splash screen (much like Element Android) and made them automatically change colour based on the theme. The former is achieved by modifying the XML style files which is easy and clean, but the latter was a little more complicated. The notification bar is always set to transparent on app start which makes it the same colour as the top app bar - this looks great. The navbar at the bottom however, when made transparent, instead shows the app primary colour. To work around this, on app start it is set to the theme colour (whiteDefault/blackDefault/blackFull) and updated on theme change too.

To be honest, I mostly did this to get familiar with the codebase as opposed to it being strictly necessary, but I still think it looks better :P

### CODE REVIEW

**Comment by TR-SLimey** [comment]
Oops, the translucent navbar makes the home FAB look weird. I'll convert to draft while I fix that.

**Comment by ereio** [comment]
I like how it looks too 👍

If the contrast is an issue for accessibility (I'd have to research it but that's the only problem I could see with it), we can make it toggleable.

**Comment by TR-SLimey** [comment]
I've made some changes (see edited original comment) and it seems to be working very well. I decided to try working on a theme refactor separately, which might affect some of this code eventually. As for contrast, I think that should be fine, since a lot of other apps also blend in with the system UI.

**Comment by TR-SLimey** [comment]
Also, here's a demo of the changes I've made: https://be.an-atom-in.space/s/GTNRnPtispdeXAT
I couldn't upload it here since it's over 10MB so I put it on my NextCloud instead.

**Review by ereio — APPROVED** [review]
I may move the switch block into a function called "initSystemTheme" to reduce the duplicate of the same logic. No need to do anything else, just a note. Looks good and thanks for your wok on it :)

**Comment by ereio** [comment]
* Tested working on both iOS and Android

**Pull request merged**
