### PR TITLE
[fix] linux storage issues

### PR DESCRIPTION
**Pull request by ereio**
### Types
- [x] Fix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking change which improves code quality - QA thoroughly )
- [ ] Breaking Change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Chore (updates that would not affect or change the code involving the app itself)

### QA

- [ ] Signup
- [ ] Login
- [ ] Logout
- [ ] Unencrypted Chat 
- [ ] Encrypted Chat 
- [ ] Group Chats
- [ ] Profile Changes
- [ ] Theming Changes
- [ ] Force Kill and Restart

### Final Checklist
 
- [ ] All associated issues have been linked to PR
- [ ] All necessary changes made to the documentation
- [ ] Parties interested in these changes have been notified
- [ ] Linter has been run on all code in the PR

### CODE REVIEW

**Comment by canadianotaku** [comment]
Error after login, Syphon doesn't load the profile picture, rooms, etc:
```
** (syphon:11669): CRITICAL **: 17:16:00.273: void update_pressing_state(FlKeyEmbedderResponder *, uint64_t, uint64_t): assertion 'lookup_hash_table(self->pressing_records, physical_key) == 0' failed
flutter: Null check operator used on a null value
flutter: #0      ProfileScreenState.onMounted (package:syphon/views/home/profile/profile-screen.dart:46)
flutter: #1      _StoreStreamListenerState.initState.<anonymous closure> (package:flutter_redux/flutter_redux.dart:475)
flutter: #2      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144)
flutter: #3      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1089)
flutter: #4      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995)
flutter: #8      _invoke (dart:ui/hooks.dart:151)
flutter: #9      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308)
flutter: #10     _drawFrame (dart:ui/hooks.dart:115)
flutter: (elided 3 frames from dart:async)
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
```

**Comment by ereio** [comment]
very strange, not seeing that on my ubuntu LTS box but I'll try to recreate. What distro are you using? feel free to post about it in syphon dev too

**Comment by canadianotaku** [comment]
> very strange, not seeing that on my ubuntu LTS box but I'll try to recreate. What distro are you using? feel free to post about it in syphon dev too

forgot to say, gentoo linux

**Comment by ereio** [comment]
@canadianotaku going to break out that issue into another seeing as it's no longer a storage problem

**Pull request merged**
