### PR TITLE
[feature] Support 3pids (email/msisdn) for logins

### PR DESCRIPTION
**Pull request by EdGeraghty**
### Types
 - [ ]  Bug fix (non-breaking change which fixes an issue)
 - [x]  New feature (non-breaking change which adds functionality)
 - [ ]  Refactoring (fix or feature that would cause existing functionality to not work as expected)
 - [ ]  Breaking change (non-breaking change which improves code quality - QA thoroughly)

#### 🔮 Features
- Allow login with 3pids (Third-Party IDs)
### QA
 - [ ]  Signup
 - [x]  Login
 - [x]  Logout
 - [ ]  Unencrypted Chat
 - [ ]  Encrypted Chat
 - [ ]  Group Chats
 - [ ]  Profile Changes
 - [ ]  Theming Changes
 - [ ]  Force Kill and Restart

### Final Checklist
 - [x]  All associated issues have been linked to PR
 - [ ]  All necessary changes made to the documentation
 - [x]  Parties interested in these changes have been notified

### CODE REVIEW

**Comment by EdGeraghty** [comment]
I believe this should do the job, as laid out in the spec. I've tested that normal username login works, but I can't test email/phone as I don't have either of those against my account.

**Comment by ereio** [comment]
i'll try this out on sunday, would like to do a bit more QA surrounding it just in case

looks good tho!

**Comment by ereio** [comment]
merge https://github.com/EdGeraghty/syphon/pull/4 and I'll merge for 0.2.9

**Comment by EdGeraghty** [comment]
Done. Thanks for looking!

**Review by ereio — APPROVED** [review]

**Pull request merged**
