### PR TITLE
[fix] Small fixes

### PR DESCRIPTION
**Pull request by simplepad**
### Types
- [x] Fix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking change which improves code quality - QA thoroughly )
- [ ] Breaking Change (fix or feature that would cause existing functionality to not work as expected)
- [x] Chore (updates that would not affect or change the code involving the app itself)

#### 🐛 Fixes
Fixed missing translation, closes https://github.com/syphon-org/syphon/issues/533
Show encryption enabling warning only when turning it on, closes https://github.com/syphon-org/syphon/issues/522 
Made notifications style type descriptions translatable, also corrected translations, closes https://github.com/syphon-org/syphon/issues/532
Fixed notification service crashing on start on Android, closes https://github.com/syphon-org/syphon/issues/535
#### 📐 Refactoring

Bump Gradle version to 7.1.0
Bump flutter_secure_storage version to ^5.0.2 (needed for compatibility with the new Gradle version)

### QA

- [ ] Signup
- [ ] Login
- [ ] Logout
- [ ] Unencrypted Chat 
- [ ] Encrypted Chat 
- [x] Group Chats
- [ ] Profile Changes
- [ ] Theming Changes
- [ ] Force Kill and Restart

### Final Checklist
 
- [x] All associated issues have been linked to PR
- [x] All necessary changes made to the documentation
- [x] Parties interested in these changes have been notified

### CODE REVIEW

**Comment by ereio** [comment]
@simplepad this looks great so far, really appreciate your contributions lately! Please DM me at @ereio:matrix.org so we can add you to the dev room for coordination.

**Comment by simplepad** [comment]
Background notification service on Android is still kinda flakey, needs more work, the "Background connection enabled" notification disappears sometimes, for example launch app -> notif appears -> press home button (app stays in background) -> notif still present -> go back into the app -> notification disappears only to reappear shortly after.

**Comment by ereio** [comment]
I imagine there's also other issues with the notification service due to some of the fairly recent storage changes. Will be taking a look soon!

**Comment by ereio** [comment]
Going to run this build through drone first before merging, should get to it later today.

**Review by ereio — APPROVED** [review]

**Comment by ereio** [comment]
@simplepad can you confirm, once the latest build runs under the dev branch, that everything is working as expected? I'll be able to test Sunday (currently moving) so either way I can check it out then

**Comment by ereio** [comment]
Drone pipeline for reference

https://ci.syphon.org/syphon-org/syphon

**Comment by simplepad** [comment]
Build failed, the gradle version in gradle-wrapper needs to be changed https://github.com/syphon-org/syphon/pull/547

**Comment by simplepad** [comment]
Alright, just tested the build and everything works as expected as far as I can see.

**Pull request merged**
