### PR TITLE
[fix] show terms of service only once

### PR DESCRIPTION
**Pull request by simplepad**
### Types
- [x] Fix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking change which improves code quality - QA thoroughly )
- [ ] Breaking Change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Chore (updates that would not affect or change the code involving the app itself)

#### 🐛 Fixes
Only show Terms of Service once, closes https://github.com/syphon-org/syphon/issues/519
### QA

- [ ] Signup
- [x] Login
- [x] Logout
- [ ] Unencrypted Chat 
- [ ] Encrypted Chat 
- [ ] Group Chats
- [ ] Profile Changes
- [ ] Theming Changes
- [ ] Force Kill and Restart

### Final Checklist
 
- [ ] All associated issues have been linked to PR
- [ ] All necessary changes made to the documentation
- [ ] Parties interested in these changes have been notified

### CODE REVIEW

**Comment by simplepad** [comment]
Right now, user logout wipes all the settings clean, is this a bug or by design? @ereio

**Comment by ereio** [comment]
The original check was supposed to look for if the `alphaAgreement` timestamp was non-null (would function the same as the boolean here).

Everything should get cleared from settings except for that `alphaAgreement` timestamp. Correcting that should fix the issue but lmk if it doesn't! Thanks for taking a look into this!

**Comment by simplepad** [comment]
Ok, tested now and it finally works. Unfortunately, had to switch to using SharedPreferences (platform agnostic) for persistent saving of the agreement to ToS. Tried many things with the settigns store but it wipes everything on log-out, no matter what I tried.

**Comment by ereio** [comment]
Thanks for looking into this. You're correct in that settings no longer works for storing this value since most of the stores (both the current account and the default) are cleared on logout.

We do already use `flutter_secure_storage` for key/value pairs across all platforms. If you want to save a one off value like this (though it's rare since most should be saved alongside state), I'd recommend it. I've gone ahead and pushed a fix based off your changes here but with `flutter_secure_store`. Still happy to credit you for the work; you brought the issue to our attention!

https://github.com/syphon-org/syphon/pull/568/commits/79bb9ba526a8a4ee530afe1f7c591ed64478eeed

**Comment by ereio** [comment]
reference #568

**Pull request closed without merging**
