### PR TITLE
[fix] "connected" devices without Internet Connection now respect backoff

### LINKED ISSUE #665: Offline exponential backoff iterates too quickly
Perhaps in addition to reducing the backoff, we should have a way for the user to force the client to attempt reconnection; being offline for a few minutes with the client running makes it inoperable without restarting it

### PR DESCRIPTION
**Pull request by EdGeraghty**
### Types
- [x] Fix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking change which improves code quality - QA thoroughly )
- [ ] Breaking Change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Chore (updates that would not affect or change the code involving the app itself)

#### 🐛 Fixes
e.g. WiFi connected devices on VPNs, behind portals, proxies, or other captive method which don't _actually_ possess a route to the Internet (fixes #665)
### QA

- [ ] Signup
- [ ] Login
- [ ] Logout
- [ ] Unencrypted Chat 
- [ ] Encrypted Chat 
- [ ] Group Chats
- [ ] Profile Changes
- [ ] Theming Changes
- [ ] Force Kill and Restart

### Final Checklist
 
- [x] All associated issues have been linked to PR
- [ ] All necessary changes made to the documentation
- [ ] Parties interested in these changes have been notified
- [x] Linter has been run on all code in the PR

### CODE REVIEW

**Comment by ereio** [comment]
Note this block of code here is just meant to ignore the backoff when the device reconnected to WIFI or an established cell connection.

If we're checking for offline to be `false` here, it means that the last `/sync' call completed successfully. Adding this in would prevent the backoff ignore in that case. I think we need to rework this in general for if someone has enabled a proxy or internet is available, but it cannot connect the homeserver. Maybe a `/_matrix/client/versions` http request as a check to differentiate those cases?

**Comment by ereio** [comment]
Could also check connectivity on each backoff and only reset if the connectivity state has changed since the last attempt. That way we would know if you weren't connected to wifi previously instead of only checking if you are now

**Comment by EdGeraghty** [comment]
The other thing to do is use a listener which fires on connection change? But it wouldn't help in this case...

**Comment by ereio** [comment]
I've done the connectivity state change in my `fix/notification-proxy` branch. 

Let's close this and work on the former - the check against `/versions` to see if a user has internet connectivity. 

Part of the reason I abstracted this library is because it doesn't actually check for internet connectivity, so really this is just "access". I was going to rename the `isConnected` function to `hasAccess` once I added something like `/version` check that looks for a 200 code or something.

**Comment by ereio** [comment]
> listener which fires on connection change?

Note this is already present and can be found here

https://github.com/syphon-org/syphon/blob/dev/lib/global/connectivity.dart#L14

**Pull request closed without merging**
