### PR TITLE
Updated to the new Flathub badge

### PR DESCRIPTION
**Pull request by Danik1601**
Similar to the [website's landing page change](https://github.com/syphon-org/landing/pull/26/commits/109c980817e62db0a5b32a876bcb390c846604d0)

### CODE REVIEW

**Comment by 0x1a8510f2** [comment]
Both links look the same to me. Any particular reason to use one over the other?

For reference:

``


``

**Comment by Danik1601** [comment]
> Both links look the same to me. Any particular reason to use one over the other?

[Flathub](https://flathub.org/) has gone through [rebranding](https://blog.jimmac.eu/2023/flathub-brand-refresh/). It has the brand new logo which is reflected in the new [badge guideline](https://flathub.org/badges).

**Comment by dnisbetjones** [comment]
@0x1a8510f2 

The updated logo may not have reached you yet. I also didn't see any difference looking at the two images on mobile but I screenshotted it for you here:

image

**Comment by 0x1a8510f2** [comment]
I actually have the new logo at both links lol:

image

But if the logo is different for some people, happy with the change.

**Comment by Danik1601** [comment]
> @0x1a8510f2
> 
> The updated logo may not have reached you yet. I also didn't see any difference looking at the two images on mobile but I screenshotted it for you here:
> 


Oh, I haven't realized that they actually look as the same image for you. But yes, refer to the screenshot

**Review by 0x1a8510f2 — APPROVED** [review]

**Comment by Danik1601** [comment]
> I actually have the new logo at both links lol:
>

I don't understand a thing then...

But anyway I am happy that the change is approved. Thanks

**Pull request merged**
