### PR TITLE
[fix] Check SRV record as alternative to .well-known

### PR DESCRIPTION
**Pull request by EdGeraghty**
### Types
- [x] Fix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking change which improves code quality - QA thoroughly )
- [ ] Breaking Change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Chore (updates that would not affect or change the code involving the app itself)

#### 🐛 Fixes
Check SRV record if `.well-known` client file is missing
### QA

- [ ] Signup
- [ ] Login
- [ ] Logout
- [ ] Unencrypted Chat 
- [ ] Encrypted Chat 
- [ ] Group Chats
- [ ] Profile Changes
- [ ] Theming Changes
- [ ] Force Kill and Restart

### Final Checklist
 
- [x] All associated issues have been linked to PR
- [ ] All necessary changes made to the documentation
- [x] Parties interested in these changes have been notified
- [x] Linter has been run on all code in the PR

### CODE REVIEW

**Review by ereio — DISMISSED** [review]
Good work!

**Review by ereio — COMMENTED** [review]
Does this work with the proxy settings enabled?

**Comment by EdGeraghty** [comment]
> Does this work with the proxy settings enabled?

Not at the minute. I think before merging I need to try and build an upstream method to allow us to set our own HttpClient object. I'm also not massively happy that this "solution" requires Google's Public DNS.

**Comment by EdGeraghty** [comment]
If you know of a way to interrogate SRV records without needing this additional library, I'm all ears :)

**Comment by ereio** [comment]
good to know, lets wait on a merge for now then

**Comment by EdGeraghty** [comment]
I have switched to using our HttpClient to do a DoH query. Much nicer.

**Comment by EdGeraghty** [comment]
I'm going to re-work the logic so it tries the two .well-known files, then asks for permission to ping the resolver before it tries the SRV record.

**Comment by EdGeraghty** [comment]
See the conversation [on the linked issue](https://github.com/syphon-org/syphon/issues/709)

**Comment by ereio** [comment]
Since we'd have to hit cloudflare or another provider to check this, I'm inclined to just archive this for now though I like the idea. Let's keep the branch alive but close the PR if you're ok with that path forward

**Pull request closed without merging**
